### PR TITLE
Add audio encoding

### PR DESCRIPTION
**Pull request by gndl**
This pull request add the audio encoding.
Error handling is modified to prevent an exception from being thrown when the runtime system is released.
A bug concerning the sample format with the bigarrays in the Swresample module is also fixed.

### CODE REVIEW

**Comment by toots** [comment]
Wow, that looks great. Let's see if @smimram has a moment to review this :-)

**Comment by smimram** [comment]
To be honnest, I don't think I will have time to review this in details anytime soon. That being said, I skimmed through the diff and it looks superficially fine to me. So, if this patch does not deeply break the interface and the various tests pass, I would go for a merge :)

**Comment by gndl** [comment]
Thank you for the review. This PR slightly modifies the interface of my previous PR but this one has not been released yet. All the tests pass.
Note that this is not the final interface. Other PRs will come and modifies it a little bit.

**Comment by toots** [comment]
@smimram would you consider giving @gndl write access to the repo? If none of us has time to review, I think it's only fair..

**Comment by smimram** [comment]
Good idea! Welcome to @gndl :)

**Comment by gndl** [comment]
Thank you very much for welcoming me to the team :)
I will therefore commit this PR before submitting the following to you.

**Pull request merged**
