### PR TITLE
Add missing dependency to autoconf

### PR DESCRIPTION
**Pull request by kit-ty-kate**
Sorry I forgot about this one in the last PR

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Also it seems that the dev version now requires OCaml >= 4.04. Should I add that to the opam file ?

```
# /home/opam/.opam/system/lib/ffmpeg/libffmpeg_stubs.a(swresample_stubs.o): In function `convert_to_float_array':
# swresample_stubs.c:(.text+0xa94): undefined reference to `caml_alloc_float_array'
# /home/opam/.opam/system/lib/ffmpeg/libffmpeg_stubs.a(swresample_stubs.o): In function `convert_to_planar_float_array':
# swresample_stubs.c:(.text+0xe51): undefined reference to `caml_alloc_float_array'
```

**Comment by toots** [comment]
Merging the dexpext. As for the OCaml versioning, I'll let @gndl comment. He's leading the dev on this now and perhaps he wants to do something else like having a backward compatible implementation.

**Comment by gndl** [comment]
@smimram, do you need OCaml backward compatibility (I remember you did this [commit](https://github.com/savonet/ocaml-ffmpeg/commit/cbc29b4fc4e33363b1fe5b04626f15ea2b8774ed) for this purpose). I agree to define the required OCaml version to 4.04 if it suits everyone or replace caml_alloc_float_array by caml_alloc if it is necessary.

**Comment by toots** [comment]
I think we can go with `>= 4.04` too. Unless @smimram objects, feel free to go ahead this way (he might be busy these days).

**Comment by smimram** [comment]
I'm fine with dropping backward compatibility a bit. In those days opam did not exist :)

As a side note Debian stable has OCaml 4.02.3, but if it's too much of a hassle to stay compatible with that then go for 4.04.

**Pull request merged**
