### PR TITLE
Video encoding

### PR DESCRIPTION
**Pull request by gndl**
This pull request add the video encoding.

### CODE REVIEW

**Comment by gndl** [comment]
The Travis CI build failed due to incompatibilities with C89 (among others). Is it necessary to be C89 compliant ?

**Comment by toots** [comment]
I don't think it's required but if it's just for a couple of variable declarations outside of a loop, I think it's fine to fix it.

There seem to be a couple of warnings as well, would be nice to fix them too.

**Comment by gndl** [comment]
For information, in module Av, I use the new encoding and decoding interface of ffmpeg. This interface does not exist in the version present on the CIP, the modules Av and Avcodec are therefore not compiled on Travis.
If it's good for you, I'll merge this PR.

**Comment by toots** [comment]
This looks good to me, thanks for working on this! Generally speaking, I agree with targeting the latest released API when working on such bindings. Most often, your code will sit for a while after it is released and you'll be happy that it stays relevant longer. I'd suggest bumping the version, tho, since this is a pretty big API change.

**Comment by gndl** [comment]
Would version 0.2.0 be appropriate?

**Comment by toots** [comment]
Seems like it to me. We try to follow [semantic versioning](http://semver.org/) as general guide lines although I'm pretty sure minor version bumps have also been used for incompatible API changes before.

**Comment by gndl** [comment]
I'm not sure there is incompatible API changes compared to the previous release. It seems to me that there are only new functionalities.

**Comment by toots** [comment]
So `0.2.0` is definitely acceptable ;-)

**Pull request merged**
